<a href="https://colab.research.google.com/github/kailashchaudhary-p/Daily-Expense-Analyzer/blob/main/Daily_Expense_Analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
try:
  df=pd.read_csv("/content/Transactions.csv")
  print(f"data set load succesfully . shape :{df.shape}")
except Exception as e:
  print(f"Error loading the data set : {e}")
df.head()

data set load succesfully . shape :(2461, 8)

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
0,20/09/2018 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR
1,20/09/2018 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR
2,19/09/2018,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR
3,17/09/2018 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR
4,16/09/2018 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR

In [ ]:
df.tail()

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
2456,1/1/2015,Cash,Transportation,NaN,share jeep - Place T base to top,20.0,Expense,INR
2457,1/1/2015,Cash,Transportation,NaN,share auto - Place H to Place T base,20.0,Expense,INR
2458,1/1/2015,Cash,Transportation,NaN,bus - brc to Place H,30.0,Expense,INR
2459,1/1/2015,Cash,Food,NaN,tea,10.0,Expense,INR
2460,1/1/2015,Cash,Transportation,NaN,share auto - hospital to brc station,10.0,Expense,INR

In [ ]:
df.columns

Index(['Date', 'Mode', 'Category', 'Subcategory', 'Note', 'Amount',
       'Income/Expense', 'Currency'],
      dtype='object')

In [ ]:
df.isnull().sum()

Date                0
Mode                0
Category            0
Subcategory       635
Note              521
Amount              0
Income/Expense      0
Currency            0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2461 entries, 0 to 2460
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2461 non-null   object
 1   Mode            2461 non-null   object
 2   Category        2461 non-null   object
 3   Subcategory     1826 non-null   object
 4   Note            1940 non-null   object
 5   Amount          2461 non-null   float64
 6   Income/Expense  2461 non-null   object
 7   Currency        2461 non-null   object
dtypes: float64(1), object(7)
memory usage: 153.9+ KB

In [ ]:
df["Mode"].unique()

array(['Cash', 'Saving Bank account 1', 'Credit Card',
       'Equity Mutual Fund B', 'Debit Card', 'Share Market Trading',
       'Saving Bank account 2', 'Equity Mutual Fund C',
       'Equity Mutual Fund A', 'Equity Mutual Fund D', 'Fixed Deposit',
       'Recurring Deposit'], dtype=object)

In [ ]:
df['Category'].unique()

array(['Transportation', 'Food', 'subscription', 'Festivals', 'Other',
       'Small Cap fund 2', 'Small cap fund 1', 'Family',
       'Equity Mutual Fund E', 'Apparel', 'Public Provident Fund',
       'Saving Bank account 1', 'Gift', 'Salary', 'Household',
       'Dividend earned on Shares', 'Interest', 'Life Insurance',
       'Beauty', 'Health', 'Money transfer', 'maid', 'Culture',
       'Tax refund', 'Tourism', 'Share Market', 'Self-development',
       'Amazon pay cashback', 'Education', 'scrap', 'Petty cash',
       'Documents', 'Gpay Reward', 'Social Life', 'Equity Mutual Fund A',
       'Maturity amount', 'Fixed Deposit', 'Equity Mutual Fund C',
       'Equity Mutual Fund F', 'Recurring Deposit',
       'Saving Bank account 2', 'Equity Mutual Fund D',
       'Equity Mutual Fund B', 'Bonus', 'Investment', 'Grooming', 'Rent',
       'Cook', 'garbage disposal', 'water (jar /tanker)'], dtype=object)

In [ ]:
df['Income/Expense'].unique()

array(['Expense', 'Transfer-Out', 'Income'], dtype=object)

In [ ]:
df.duplicated().sum()

np.int64(9)